# Generated by Django 2.2.5 on 2020-04-18 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='专题标题')),
                ('intro', models.TextField(verbose_name='描述')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('is_show', models.BooleanField(default=1, verbose_name='是否展示')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='照片路径')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='照片描述')),
                ('upload_time', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('is_show', models.BooleanField(default=1, verbose_name='是否显示')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Album', verbose_name='所属专题')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='文章标题')),
                ('abstract', models.TextField(verbose_name='文章摘要')),
                ('content_md', models.TextField(verbose_name='md文章内容')),
                ('content_html', models.TextField(verbose_name='html文章内容')),
                ('sort', models.CharField(max_length=128, verbose_name='分类')),
                ('tags', models.CharField(max_length=256, verbose_name='标签')),
                ('create_time', models.DateField(verbose_name='创建时间')),
                ('is_show', models.BooleanField(default=1, verbose_name='是否显示')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User', verbose_name='作者')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User', verbose_name='发布者'),
        ),
    ]
