# Generated by Django 2.2.5 on 2020-04-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nic_name',
        ),
    ]
