# Generated by Django 2.2.5 on 2020-04-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_user_nic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='http://q90vhkwl9.bkt.clouddn.com/010a2b564548466ac7259e0fe9566e.jpg%402o.jpg', verbose_name='头像地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nic_name',
            field=models.CharField(default='maguodong', max_length=128, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
