# Generated by Django 2.2.5 on 2020-04-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200421_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='评论用户ID')),
                ('parent', models.BigIntegerField(default=0, verbose_name='父级评论')),
                ('reply', models.BigIntegerField(default=0, verbose_name='被回复评论')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Article', verbose_name='文章')),
            ],
        ),
    ]
