# Generated by Django 2.2.5 on 2020-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200421_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.TextField(blank=True, null=True, verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='user',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='网址'),
        ),
    ]
